# Generated by Django 4.1.2 on 2023-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comments_remove_blogpost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
