# Generated by Django 4.1.2 on 2023-04-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comments_date_alter_customerdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
