# Generated by Django 4.1.2 on 2023-04-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_reply_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply_comment',
        ),
    ]
